# Site settings
title: The Aletheia Proof Assistant
email: aletheiapa@gmail.com
description: "The Aletheia Proof Assistant is a tool for interactively develop, analyze, store and share mathematical formal proofs."
baseurl: "/Aletheia"
twitter_username: aletheiapa
github_username:  quimtestar/Aletheia

# Build settings
markdown: kramdown
permalink: pretty
