# Site settings
title: The Aletheia Proof Assistant
email: aletheiapa@gmail.com
description: ""
baseurl: "/Aletheia"
twitter_username: aletheiapa
github_username:  quimtestar

# Build settings
markdown: kramdown
permalink: pretty
